[package]
name = "google_translate"
version = "0.1.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
reqwest = "0.9"
percent-encoding = "1"
serde_json = "1"
